spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/shop
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/shop
    username: boot
    password: 1234

  devtools:
    restart:
      enabled: true

  servlet:
    multipart:
      maxFileSize: 20MB     # 파일 한개당 최대 크기
      maxRequestSize : 100MB  # 요청당 최대 파일 크기

# 파일들이 저장될 경로 ///슬러시 3개면 최상위경로
itemImgLocation: C:/shop/item
uploadPath: file:///c:/shop/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml